[package]
name = "rust_algorithms"
version = "0.1.0"
edition = "2021"
authors = ["Yuanyeex <yuanyeex@gmail.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
